/**
 * Nested workspace packages (packages/category/name) → MDX under content/docs/packages.
 * Slug remains @afenda name. SSOT: docs-V2/docs/automation.md · content.md
 * Hand-owned index.mdx is preserved; generated pages are rewritten each run.
 */
import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	statSync,
	unlinkSync,
	writeFileSync,
} from "node:fs";
import { dirname, join, normalize, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const GENERATED_BANNER =
	"{/* This file is auto-generated by `pnpm --filter @afenda/docs generate:package-docs`. Do not edit. */}";

const GITHUB_BLOB_BASE =
	"https://github.com/pohlai88/afenda-lite/blob/main";

const appDir = join(fileURLToPath(import.meta.url), "../..");
const repoRoot = join(appDir, "../..");
const packagesDir = join(repoRoot, "packages");
const contentPackagesDir = join(appDir, "content/docs/packages");
const indexPath = join(contentPackagesDir, "index.mdx");
const metaPath = join(contentPackagesDir, "meta.json");

interface PackageJson {
	readonly name?: string;
	readonly description?: string;
	readonly exports?: Record<string, unknown>;
}

interface DiscoveredPackage {
	readonly dirName: string;
	readonly packageName: string;
	readonly slug: string;
	readonly description: string | undefined;
	readonly exportPaths: readonly string[];
	readonly readmePath: string | null;
	readonly packageDir: string;
}

function fail(message: string): never {
	console.error(`[generate:package-docs] ${message}`);
	process.exit(1);
}

function yamlDoubleQuoted(value: string): string {
	return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function firstParagraph(markdown: string): string | undefined {
	const withoutFrontmatter = markdown.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/, "");
	const withoutHeading = withoutFrontmatter.replace(/^#\s+[^\n]+\r?\n+/, "");
	const match = withoutHeading.match(/^([^\n#][^\n]*(?:\r?\n(?![#\n])[^\n]*)*)/m);
	if (!match) {
		return undefined;
	}
	const text = match[1]
		.replace(/\r?\n/g, " ")
		.replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
		.replace(/`([^`]+)`/g, "$1")
		.replace(/\s+/g, " ")
		.trim();
	return text.length > 0 ? text : undefined;
}

function stripLeadingH1(markdown: string): string {
	return markdown.replace(/^#\s+[^\n]+\r?\n+/, "").trimStart();
}

function exportPathsFromPackageJson(pkg: PackageJson): string[] {
	const exportsField = pkg.exports;
	if (exportsField === undefined || typeof exportsField !== "object") {
		return ["."];
	}
	return Object.keys(exportsField).toSorted((a, b) => {
		if (a === ".") {
			return -1;
		}
		if (b === ".") {
			return 1;
		}
		return a.localeCompare(b);
	});
}

function resolveRepoRelative(fromFile: string, href: string): string | null {
	const withoutHash = href.split("#")[0] ?? href;
	const hash = href.includes("#") ? `#${href.split("#").slice(1).join("#")}` : "";
	if (withoutHash.length === 0) {
		return null;
	}
	const absolute = normalize(resolve(dirname(fromFile), withoutHash));
	const rel = relative(repoRoot, absolute).replaceAll("\\", "/");
	if (rel.startsWith("..") || rel.length === 0) {
		return null;
	}
	return `${rel}${hash}`;
}

function rewriteOutboundLinks(markdown: string, readmePath: string): string {
	return markdown.replace(
		/\[([^\]]*)\]\(([^)]+)\)/g,
		(full, label: string, href: string) => {
			const trimmed = href.trim();
			if (
				trimmed.startsWith("http://") ||
				trimmed.startsWith("https://") ||
				trimmed.startsWith("mailto:") ||
				trimmed.startsWith("#") ||
				trimmed.startsWith("/docs")
			) {
				return full;
			}
			if (trimmed.startsWith("/")) {
				return full;
			}
			const repoRel = resolveRepoRelative(readmePath, trimmed);
			if (repoRel === null) {
				return full;
			}
			return `[${label}](${GITHUB_BLOB_BASE}/${repoRel})`;
		},
	);
}

function discoverPackages(): DiscoveredPackage[] {
	if (!existsSync(packagesDir)) {
		fail(`packages directory missing at ${packagesDir}`);
	}
	const out: DiscoveredPackage[] = [];

	const candidateDirs: Array<{ dirName: string; packageDir: string }> = [];
	for (const entry of readdirSync(packagesDir)) {
		const entryDir = join(packagesDir, entry);
		if (!statSync(entryDir).isDirectory()) {
			continue;
		}
		if (existsSync(join(entryDir, "package.json"))) {
			candidateDirs.push({ dirName: entry, packageDir: entryDir });
			continue;
		}
		for (const child of readdirSync(entryDir)) {
			const packageDir = join(entryDir, child);
			if (
				statSync(packageDir).isDirectory() &&
				existsSync(join(packageDir, "package.json"))
			) {
				candidateDirs.push({
					dirName: `${entry}/${child}`,
					packageDir,
				});
			}
		}
	}

	for (const { dirName, packageDir } of candidateDirs) {
		const packageJsonPath = join(packageDir, "package.json");
		const pkg = JSON.parse(readFileSync(packageJsonPath, "utf8")) as PackageJson;
		if (typeof pkg.name !== "string" || !pkg.name.startsWith("@afenda/")) {
			continue;
		}
		const slug = pkg.name.slice("@afenda/".length);
		if (slug.length === 0 || slug.includes("/")) {
			fail(`unsupported package name ${pkg.name} in ${dirName}`);
		}
		const readmePath = join(packageDir, "README.md");
		const hasReadme = existsSync(readmePath);
		let description = pkg.description?.trim();
		if ((description === undefined || description.length === 0) && hasReadme) {
			description = firstParagraph(readFileSync(readmePath, "utf8"));
		}
		out.push({
			dirName,
			packageName: pkg.name,
			slug,
			description:
				description !== undefined && description.length > 0
					? description
					: undefined,
			exportPaths: exportPathsFromPackageJson(pkg),
			readmePath: hasReadme ? readmePath : null,
			packageDir,
		});
	}
	return out.toSorted((a, b) => a.slug.localeCompare(b.slug));
}

function renderExportsTable(
	packageName: string,
	exportPaths: readonly string[],
): string {
	const rows = exportPaths.map((exportPath) => {
		const importPath =
			exportPath === "." ? packageName : `${packageName}${exportPath.slice(1)}`;
		return `| \`${importPath}\` | \`${exportPath}\` |`;
	});
	return [
		"## Package exports",
		"",
		"| Import path | Export key |",
		"| --- | --- |",
		...rows,
		"",
	].join("\n");
}

function renderPackageMdx(pkg: DiscoveredPackage): string {
	const description =
		pkg.description ??
		`Workspace package \`${pkg.packageName}\` — regenerate with generate:package-docs.`;
	const parts: string[] = [
		"---",
		`title: ${yamlDoubleQuoted(pkg.packageName)}`,
		`description: ${yamlDoubleQuoted(description)}`,
		"---",
		"",
		GENERATED_BANNER,
		"",
		"<Callout type=\"info\" title=\"Generated from packages\">",
		`  Source: \`packages/${pkg.dirName}/\` · regenerate with`,
		"  `pnpm --filter @afenda/docs generate:package-docs`.",
		"</Callout>",
		"",
		renderExportsTable(pkg.packageName, pkg.exportPaths),
	];

	if (pkg.readmePath !== null) {
		const raw = readFileSync(pkg.readmePath, "utf8");
		const body = rewriteOutboundLinks(stripLeadingH1(raw), pkg.readmePath).trim();
		if (body.length > 0) {
			parts.push("## Package README", "", body, "");
		}
	}

	return `${parts.join("\n").trimEnd()}\n`;
}

function ensureHandIndex(): void {
	if (existsSync(indexPath)) {
		const existing = readFileSync(indexPath, "utf8");
		if (existing.includes(GENERATED_BANNER)) {
			fail(
				"content/docs/packages/index.mdx is hand-owned and must not contain the generated banner",
			);
		}
		return;
	}
	fail(
		"content/docs/packages/index.mdx missing — create the hand-owned landing page before generate",
	);
}

const packages = discoverPackages();
if (packages.length === 0) {
	fail("no @afenda/* packages discovered under packages/");
}

mkdirSync(contentPackagesDir, { recursive: true });
ensureHandIndex();

const preservedIndex = readFileSync(indexPath, "utf8");
const slugs = packages.map((pkg) => pkg.slug);

for (const pkg of packages) {
	writeFileSync(
		join(contentPackagesDir, `${pkg.slug}.mdx`),
		renderPackageMdx(pkg),
		"utf8",
	);
}

writeFileSync(indexPath, preservedIndex, "utf8");

const meta = {
	title: "Packages",
	icon: "Package",
	pages: ["index", ...slugs],
};
writeFileSync(metaPath, `${JSON.stringify(meta, null, "\t")}\n`, "utf8");

const kept = new Set(meta.pages);
for (const name of readdirSync(contentPackagesDir)) {
	if (!name.endsWith(".mdx")) {
		continue;
	}
	const slug = name.replace(/\.mdx$/, "");
	if (!kept.has(slug)) {
		unlinkSync(join(contentPackagesDir, name));
	}
}

console.log(
	`generate:package-docs: wrote ${String(packages.length)} package pages under content/docs/packages`,
);
