import { PORTAL_NAME } from "@/lib/portal-copy";

/** Compressed 512×512 brand disk for in-app marks (next/image optimizes further). */
export const BRAND_ICON_PATH = "/brandicondisk.png";
export const BRAND_ICON_WIDTH = 512;
export const BRAND_ICON_HEIGHT = 512;

/** Browser-level icon assets (generated by `npm run icons:generate`). */
export const BRAND_FAVICON_16_PATH = "/icons/favicon-16.png";
export const BRAND_FAVICON_32_PATH = "/icons/favicon-32.png";
export const BRAND_APPLE_ICON_PATH = "/icons/apple-touch-icon.png";
export const BRAND_PWA_ICON_192_PATH = "/icons/icon-192.png";
export const BRAND_PWA_ICON_512_PATH = "/icons/icon-512.png";
export const BRAND_OG_IMAGE_PATH = "/icons/og-image.png";
export const BRAND_OG_IMAGE_WIDTH = 512;
export const BRAND_OG_IMAGE_HEIGHT = 512;
export const BRAND_WEB_MANIFEST_PATH = "/site.webmanifest";

export const BRAND_MARK_NAME = "iAM";
export const BRAND_ICON_ALT = `${BRAND_MARK_NAME} — ${PORTAL_NAME} logo`;
