/**
 * ARCH-023 hard tenant roots after domain wipe.
 * Every table has `organization_id … NOT NULL` — CI: `pnpm audit:tenancy-nulls`.
 */
import {
	mdChangeRequest,
	mdItem,
	mdItemAlias,
	mdItemBarcode,
	mdItemExternalId,
	mdItemGroup,
	mdItemTemplate,
	mdItemTemplateAttribute,
	mdItemTemplateAttributeOption,
	mdItemUom,
	mdItemVariant,
	mdItemVariantAttributeValue,
	mdParty,
	mdPartyAddress,
	mdPartyContact,
	mdPartyExternalId,
	mdPartyRelationship,
	mdPartyRole,
	mdPaymentTerm,
	mdTaxRegistration,
	mdWarehouse,
	mdWarehouseExternalId,
} from "./schema/master-data";
import {
	platformAuditLog,
	platformDomainEvent,
	platformNotification,
	platformRbacAudit,
	platformRoleAssignment,
	platformSearchDocument,
} from "./schema/platform";
import {
	stockBalance,
	stockLedgerEntry,
	stockMovement,
	stockMovementLine,
	stockReservation,
} from "./schema/inventory";
import { purchaseOrder, purchaseOrderLine } from "./schema/purchasing";
import { salesOrder, salesOrderLine } from "./schema/sales";

/** SQL table names for null-org audits (RB-001 §3.4 · ARCH-023). */
export const HARD_TENANT_ROOT_TABLE_NAMES = [
	"platform_role_assignment",
	"platform_rbac_audit",
	"platform_audit_log",
	"platform_search_document",
	"platform_notification",
	"platform_domain_event",
	"md_party",
	"md_item_group",
	"md_item",
	"md_warehouse",
	"md_payment_term",
	"md_tax_registration",
	"md_party_role",
	"md_party_address",
	"md_party_contact",
	"md_party_external_id",
	"md_party_relationship",
	"md_item_uom",
	"md_item_barcode",
	"md_item_external_id",
	"md_item_alias",
	"md_warehouse_external_id",
	"md_item_template",
	"md_item_template_attribute",
	"md_item_template_attribute_option",
	"md_item_variant",
	"md_item_variant_attribute_value",
	"md_change_request",
	"sales_order",
	"sales_order_line",
	"purchase_order",
	"purchase_order_line",
	"stock_movement",
	"stock_movement_line",
	"stock_balance",
	"stock_ledger_entry",
	"stock_reservation",
] as const;

export type HardTenantRootTableName =
	(typeof HARD_TENANT_ROOT_TABLE_NAMES)[number];

/** Drizzle table refs for schema contract tests. */
export const HARD_TENANT_ROOT_TABLES = {
	platformRoleAssignment,
	platformRbacAudit,
	platformAuditLog,
	platformSearchDocument,
	platformNotification,
	platformDomainEvent,
	mdParty,
	mdItemGroup,
	mdItem,
	mdWarehouse,
	mdPaymentTerm,
	mdTaxRegistration,
	mdPartyRole,
	mdPartyAddress,
	mdPartyContact,
	mdPartyExternalId,
	mdPartyRelationship,
	mdItemUom,
	mdItemBarcode,
	mdItemExternalId,
	mdItemAlias,
	mdWarehouseExternalId,
	mdItemTemplate,
	mdItemTemplateAttribute,
	mdItemTemplateAttributeOption,
	mdItemVariant,
	mdItemVariantAttributeValue,
	mdChangeRequest,
	salesOrder,
	salesOrderLine,
	purchaseOrder,
	purchaseOrderLine,
	stockMovement,
	stockMovementLine,
	stockBalance,
	stockLedgerEntry,
	stockReservation,
} as const;
