/**
 * ARCH-023 hard tenant roots after domain wipe.
 * Every table has `organization_id … NOT NULL` — CI: `pnpm audit:tenancy-nulls`.
 */

import {
	accountingPeriod,
	journal,
	journalLine,
	ledgerPosting,
} from "./schema/accounting";
import {
	delivery,
	deliveryLine,
	deliveryPack,
	deliveryPick,
	proofOfDelivery,
} from "./schema/fulfillment";
import {
	stockBalance,
	stockLedgerEntry,
	stockMovement,
	stockMovementLine,
	stockReservation,
} from "./schema/inventory";
import {
	mdChangeRequest,
	mdImportBatch,
	mdItem,
	mdItemAlias,
	mdItemBarcode,
	mdItemExternalId,
	mdItemGroup,
	mdItemTemplate,
	mdItemTemplateAttribute,
	mdItemTemplateAttributeOption,
	mdItemUom,
	mdItemVariant,
	mdItemVariantAttributeValue,
	mdParty,
	mdPartyAddress,
	mdPartyContact,
	mdPartyExternalId,
	mdPartyRelationship,
	mdPartyRole,
	mdPaymentTerm,
	mdTaxRegistration,
	mdWarehouse,
	mdWarehouseExternalId,
} from "./schema/master-data";
import {
	supplierAllocation,
	supplierBalanceProjection,
	supplierCreditNote,
	supplierInvoice,
	supplierInvoiceLine,
	threeWayMatchResult,
} from "./schema/payables";
import { payment, paymentAccount, paymentAllocation, paymentReversal } from "./schema/payments";
import {
	platformAuditLog,
	platformDomainEvent,
	platformNotification,
	platformRbacAudit,
	platformRoleAssignment,
	platformSearchDocument,
} from "./schema/platform";
import { purchaseOrder, purchaseOrderLine } from "./schema/purchasing";
import {
	customerAllocation,
	customerBalanceProjection,
	salesCreditNote,
	salesInvoice,
	salesInvoiceLine,
} from "./schema/receivables";
import {
	goodsReceipt,
	goodsReceiptLine,
	receivingDiscrepancy,
} from "./schema/receiving";
import { salesOrder, salesOrderLine } from "./schema/sales";

/** SQL table names for null-org audits (RB-001 §3.4 · ARCH-023). */
export const HARD_TENANT_ROOT_TABLE_NAMES = [
	"platform_role_assignment",
	"platform_rbac_audit",
	"platform_audit_log",
	"platform_search_document",
	"platform_notification",
	"platform_domain_event",
	"md_party",
	"md_item_group",
	"md_item",
	"md_warehouse",
	"md_payment_term",
	"md_tax_registration",
	"md_party_role",
	"md_party_address",
	"md_party_contact",
	"md_party_external_id",
	"md_party_relationship",
	"md_item_uom",
	"md_item_barcode",
	"md_item_external_id",
	"md_item_alias",
	"md_warehouse_external_id",
	"md_item_template",
	"md_item_template_attribute",
	"md_item_template_attribute_option",
	"md_item_variant",
	"md_item_variant_attribute_value",
	"md_change_request",
	"md_import_batch",
	"sales_order",
	"sales_order_line",
	"purchase_order",
	"purchase_order_line",
	"sales_invoice",
	"sales_invoice_line",
	"sales_credit_note",
	"customer_allocation",
	"customer_balance_projection",
	"supplier_invoice",
	"supplier_invoice_line",
	"supplier_credit_note",
	"supplier_allocation",
	"three_way_match_result",
	"supplier_balance_projection",
	"payment_account",
	"payment",
	"payment_allocation",
	"payment_reversal",
	"stock_movement",
	"stock_movement_line",
	"stock_balance",
	"stock_ledger_entry",
	"stock_reservation",
	"goods_receipt",
	"goods_receipt_line",
	"receiving_discrepancy",
	"delivery",
	"delivery_line",
	"delivery_pick",
	"delivery_pack",
	"proof_of_delivery",
	"journal",
	"journal_line",
	"ledger_posting",
	"accounting_period",
] as const;

export type HardTenantRootTableName =
	(typeof HARD_TENANT_ROOT_TABLE_NAMES)[number];

/** Drizzle table refs for schema contract tests. */
export const HARD_TENANT_ROOT_TABLES = {
	platformRoleAssignment,
	platformRbacAudit,
	platformAuditLog,
	platformSearchDocument,
	platformNotification,
	platformDomainEvent,
	mdParty,
	mdItemGroup,
	mdItem,
	mdWarehouse,
	mdPaymentTerm,
	mdTaxRegistration,
	mdPartyRole,
	mdPartyAddress,
	mdPartyContact,
	mdPartyExternalId,
	mdPartyRelationship,
	mdItemUom,
	mdItemBarcode,
	mdItemExternalId,
	mdItemAlias,
	mdWarehouseExternalId,
	mdItemTemplate,
	mdItemTemplateAttribute,
	mdItemTemplateAttributeOption,
	mdItemVariant,
	mdItemVariantAttributeValue,
	mdChangeRequest,
	mdImportBatch,
	salesOrder,
	salesOrderLine,
	purchaseOrder,
	purchaseOrderLine,
	salesInvoice,
	salesInvoiceLine,
	salesCreditNote,
	customerAllocation,
	customerBalanceProjection,
	supplierInvoice,
	supplierInvoiceLine,
	supplierCreditNote,
	supplierAllocation,
	threeWayMatchResult,
	supplierBalanceProjection,
	paymentAccount,
	payment,
	paymentAllocation,
	paymentReversal,
	stockMovement,
	stockMovementLine,
	stockBalance,
	stockLedgerEntry,
	stockReservation,
	goodsReceipt,
	goodsReceiptLine,
	receivingDiscrepancy,
	delivery,
	deliveryLine,
	deliveryPick,
	deliveryPack,
	proofOfDelivery,
	journal,
	journalLine,
	ledgerPosting,
	accountingPeriod,
} as const;
