import type { AfendaModuleManifest } from "@afenda/db/module-manifest";
import {
	RECEIVING_DISCREPANCY_RECORDED_EVENT,
	RECEIVING_DISCREPANCY_RESOLVED_EVENT,
	RECEIVING_RECEIPT_CANCELLED_EVENT,
	RECEIVING_RECEIPT_CREATED_EVENT,
	RECEIVING_RECEIPT_LINE_ADDED_EVENT,
	RECEIVING_RECEIPT_POSTED_EVENT,
	RECEIVING_RECEIPT_REVERSED_EVENT,
} from "@afenda/events/schemas";

import {
	RECEIVING_COMMAND_CANCEL,
	RECEIVING_COMMAND_CREATE,
	RECEIVING_COMMAND_DISCREPANCY_RECORD,
	RECEIVING_COMMAND_DISCREPANCY_RESOLVE,
	RECEIVING_COMMAND_IDS,
	RECEIVING_COMMAND_LINE_ADD,
	RECEIVING_COMMAND_POST,
	RECEIVING_COMMAND_REVERSE,
	RECEIVING_QUERY_GET,
	RECEIVING_QUERY_IDS,
	RECEIVING_QUERY_INVENTORY_EXCEPTIONS,
	RECEIVING_QUERY_LIST,
} from "./module-ids";
import {
	RECEIVING_PERMISSION_CODES,
	RECEIVING_PERMISSION_DISCREPANCY_RECORD,
	RECEIVING_PERMISSION_DISCREPANCY_RESOLVE,
	RECEIVING_PERMISSION_RECEIPT_CANCEL,
	RECEIVING_PERMISSION_RECEIPT_CREATE,
	RECEIVING_PERMISSION_RECEIPT_POST,
	RECEIVING_PERMISSION_RECEIPT_READ,
	RECEIVING_PERMISSION_RECEIPT_REVERSE,
	RECEIVING_PERMISSION_RECEIPT_UPDATE,
} from "./permissions";

export const receivingModuleManifest = {
	id: "receiving",
	category: "supply-chain",
	packageName: "@afenda/receiving",
	band: "R1-F",
	lifecycle: "active",
	activationMode: "organization_toggle",
	owns: {
		aggregates: ["goods_receipt", "receiving_discrepancy"],
		commandNamespace: "receiving.receipt",
		commands: [...RECEIVING_COMMAND_IDS],
		queryNamespace: "receiving.receipt",
		queries: [...RECEIVING_QUERY_IDS],
	},
	persistence: {
		schemaOwner: "@afenda/db",
		mutationTables: [
			"goods_receipt",
			"goods_receipt_line",
			"receiving_discrepancy",
		],
	},
	events: {
		namespace: "receiving",
		emits: [
			RECEIVING_RECEIPT_CREATED_EVENT,
			RECEIVING_RECEIPT_LINE_ADDED_EVENT,
			RECEIVING_RECEIPT_POSTED_EVENT,
			RECEIVING_RECEIPT_CANCELLED_EVENT,
			RECEIVING_RECEIPT_REVERSED_EVENT,
			RECEIVING_DISCREPANCY_RECORDED_EVENT,
			RECEIVING_DISCREPANCY_RESOLVED_EVENT,
		],
		consumes: [],
	},
	permissions: {
		namespace: "receiving",
		codes: [...RECEIVING_PERMISSION_CODES],
	},
	authorization: {
		commands: {
			[RECEIVING_COMMAND_CREATE]: RECEIVING_PERMISSION_RECEIPT_CREATE,
			[RECEIVING_COMMAND_LINE_ADD]: RECEIVING_PERMISSION_RECEIPT_UPDATE,
			[RECEIVING_COMMAND_POST]: RECEIVING_PERMISSION_RECEIPT_POST,
			[RECEIVING_COMMAND_CANCEL]: RECEIVING_PERMISSION_RECEIPT_CANCEL,
			[RECEIVING_COMMAND_REVERSE]: RECEIVING_PERMISSION_RECEIPT_REVERSE,
			[RECEIVING_COMMAND_DISCREPANCY_RECORD]:
				RECEIVING_PERMISSION_DISCREPANCY_RECORD,
			[RECEIVING_COMMAND_DISCREPANCY_RESOLVE]:
				RECEIVING_PERMISSION_DISCREPANCY_RESOLVE,
		},
		queries: {
			[RECEIVING_QUERY_GET]: RECEIVING_PERMISSION_RECEIPT_READ,
			[RECEIVING_QUERY_LIST]: RECEIVING_PERMISSION_RECEIPT_READ,
			[RECEIVING_QUERY_INVENTORY_EXCEPTIONS]: RECEIVING_PERMISSION_RECEIPT_READ,
		},
	},
	moduleDependencies: { required: ["master-data"] },
	optionalIntegratesWith: [
		{ moduleId: "purchasing", style: "ports" },
		{ moduleId: "inventory", style: "events" },
		{ moduleId: "payables", style: "events" },
	],
} as const satisfies AfendaModuleManifest;
