import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import {
  LOCAL_ONLY_KEYS,
  SECRET_KEYS,
  STALE_VERCEL_KEYS,
  VERCEL_PRODUCTION_KEYS,
} from "./env-manifest.generated.mjs";

export { LOCAL_ONLY_KEYS, SECRET_KEYS, STALE_VERCEL_KEYS, VERCEL_PRODUCTION_KEYS };

export const ENV_CONFIG_PATH = "env.config";
export const ENV_SECRET_PATH = "env.secret";
export const ENV_COMPOSED_PATH = ".env";

const COMPOSED_HEADER = `# Generated by \`npm run env:compose\` — do not edit by hand.
# Edit env.config (non-secrets) and env.secret (credentials), then re-compose.
#
# Sync strategy: see AGENTS.md → Environment variables
`;

export function parseEnvContent(content) {
  const env = {};
  const lines = [];

  for (const line of content.split("\n")) {
    lines.push(line);
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const index = trimmed.indexOf("=");
    if (index === -1) continue;
    env[trimmed.slice(0, index)] = trimmed.slice(index + 1);
  }

  return { env, lines };
}

export function parseEnvFile(path) {
  try {
    const content = readFileSync(resolve(process.cwd(), path), "utf8");
    return parseEnvContent(content).env;
  } catch {
    return {};
  }
}

export function loadComposedEnv() {
  const config = parseEnvFile(ENV_CONFIG_PATH);
  const secret = parseEnvFile(ENV_SECRET_PATH);

  if (Object.keys(config).length || Object.keys(secret).length) {
    return { ...config, ...secret };
  }

  return parseEnvFile(ENV_COMPOSED_PATH);
}

export function getEnvValue(key, fileEnv = loadComposedEnv()) {
  // env.secret / env.config win for credentials — stale shell exports must not override.
  if (SECRET_KEYS.has(key) && fileEnv[key]) {
    return fileEnv[key];
  }
  return process.env[key] ?? fileEnv[key];
}

function formatEnvFile(header, entries, sourceLines = []) {
  const blocks = [header.trimEnd(), ""];

  if (sourceLines.length > 0) {
    for (const line of sourceLines) {
      blocks.push(line);
    }
    return `${blocks.join("\n").trimEnd()}\n`;
  }

  for (const [key, value] of entries) {
    blocks.push(`${key}=${value}`);
  }

  return `${blocks.join("\n").trimEnd()}\n`;
}

export function composeEnv({ write = true } = {}) {
  const configPath = resolve(process.cwd(), ENV_CONFIG_PATH);
  const secretPath = resolve(process.cwd(), ENV_SECRET_PATH);

  if (!existsSync(configPath) && !existsSync(secretPath)) {
    throw new Error(
      `Missing ${ENV_CONFIG_PATH} and ${ENV_SECRET_PATH}. Run \`npm run env:split\` from an existing .env, or copy the *.example templates.`,
    );
  }

  const configContent = existsSync(configPath)
    ? readFileSync(configPath, "utf8")
    : "";
  const secretContent = existsSync(secretPath)
    ? readFileSync(secretPath, "utf8")
    : "";

  const config = parseEnvContent(configContent).env;
  const secret = parseEnvContent(secretContent).env;
  const merged = { ...config, ...secret };

  const body = [
    configContent.trimEnd(),
    "",
    secretContent.trimEnd(),
  ]
    .filter(Boolean)
    .join("\n");

  const output = `${COMPOSED_HEADER}\n${body}\n`;

  if (write) {
    writeFileSync(resolve(process.cwd(), ENV_COMPOSED_PATH), output, "utf8");
  }

  return merged;
}

export function splitEnv(sourcePath = ENV_COMPOSED_PATH) {
  const source = readFileSync(resolve(process.cwd(), sourcePath), "utf8");
  const { env } = parseEnvContent(source);

  const configEntries = [];
  const secretEntries = [];

  for (const [key, value] of Object.entries(env)) {
    if (SECRET_KEYS.has(key)) {
      secretEntries.push([key, value]);
    } else {
      configEntries.push([key, value]);
    }
  }

  const configHeader = `# Non-secret configuration — safe to discuss in docs and PRs.
# Compose into .env: npm run env:compose
`;

  const secretHeader = `# Secrets and credentials — never commit, never sync to public channels.
# Compose into .env: npm run env:compose
`;

  writeFileSync(
    resolve(process.cwd(), ENV_CONFIG_PATH),
    formatEnvFile(configHeader, configEntries),
    "utf8",
  );
  writeFileSync(
    resolve(process.cwd(), ENV_SECRET_PATH),
    formatEnvFile(secretHeader, secretEntries),
    "utf8",
  );

  return { configCount: configEntries.length, secretCount: secretEntries.length };
}
