import type { AfendaModuleManifest } from "@afenda/db/module-manifest";
import {
	ACCOUNTING_JOURNAL_POSTED_EVENT,
	ACCOUNTING_JOURNAL_REVERSED_EVENT,
} from "@afenda/events/schemas";

export const accountingModuleManifest = {
	id: "accounting",
	category: "commercial/finance",
	packageName: "@afenda/accounting",
	band: "R1-F",
	lifecycle: "active",
	activationMode: "organization_toggle",
	owns: {
		aggregates: [
			"journal",
			"accounting_period",
			"chart_of_account",
			"ledger_account",
			"account_role_mapping",
			"posting_profile",
			"source_posting_link",
			"financial_posting_exception",
		],
		commandNamespace: "accounting",
		commands: [
			"accounting.journal.create",
			"accounting.journal.line.add",
			"accounting.journal.post",
			"accounting.journal.reverse",
			"accounting.period.open",
			"accounting.period.soft_close",
			"accounting.period.close",
			"accounting.period.reopen",
			"accounting.chart.create",
			"accounting.ledger_account.create",
			"accounting.ledger_account.update",
			"accounting.ledger_account.deactivate",
			"accounting.account_role.map",
			"accounting.posting_profile.upsert",
			"accounting.source_event.post",
			"accounting.exception.resolve",
		],
		queryNamespace: "accounting",
		queries: [
			"accounting.journal.get",
			"accounting.journal.list",
			"accounting.trial-balance.get",
			"accounting.ledger_account.list",
			"accounting.ledger_activity.get",
			"accounting.source_trace.get",
			"accounting.exceptions.list",
		],
	},
	persistence: {
		schemaOwner: "@afenda/db",
		mutationTables: [
			"journal",
			"journal_line",
			"ledger_posting",
			"accounting_period",
			"chart_of_account",
			"ledger_account",
			"account_role_mapping",
			"posting_profile",
			"posting_profile_line",
			"source_posting_link",
			"financial_posting_exception",
		],
	},
	events: {
		namespace: "accounting",
		emits: [ACCOUNTING_JOURNAL_POSTED_EVENT, ACCOUNTING_JOURNAL_REVERSED_EVENT],
		consumes: [],
	},
	permissions: {
		namespace: "accounting",
		codes: [
			"accounting.journal.read",
			"accounting.journal.create",
			"accounting.journal.update",
			"accounting.journal.post",
			"accounting.journal.reverse",
			"accounting.trial_balance.read",
			"accounting.ledger.read",
			"accounting.period.read",
			"accounting.period.open",
			"accounting.period.soft_close",
			"accounting.period.close",
			"accounting.period.reopen",
			"accounting.account.read",
			"accounting.account.manage",
			"accounting.posting_rule.manage",
			"accounting.exception.read",
			"accounting.exception.manage",
		],
	},
	authorization: {
		commands: {
			"accounting.journal.create": "accounting.journal.create",
			"accounting.journal.line.add": "accounting.journal.create",
			"accounting.journal.post": "accounting.journal.post",
			"accounting.journal.reverse": "accounting.journal.reverse",
			"accounting.period.open": "accounting.period.open",
			"accounting.period.soft_close": "accounting.period.soft_close",
			"accounting.period.close": "accounting.period.close",
			"accounting.period.reopen": "accounting.period.reopen",
			"accounting.chart.create": "accounting.account.manage",
			"accounting.ledger_account.create": "accounting.account.manage",
			"accounting.ledger_account.update": "accounting.account.manage",
			"accounting.ledger_account.deactivate": "accounting.account.manage",
			"accounting.account_role.map": "accounting.account.manage",
			"accounting.posting_profile.upsert": "accounting.posting_rule.manage",
			"accounting.source_event.post": "accounting.journal.post",
			"accounting.exception.resolve": "accounting.exception.manage",
		},
		queries: {
			"accounting.journal.get": "accounting.journal.read",
			"accounting.journal.list": "accounting.journal.read",
			"accounting.trial-balance.get": "accounting.trial_balance.read",
			"accounting.ledger_account.list": "accounting.account.read",
			"accounting.ledger_activity.get": "accounting.ledger.read",
			"accounting.source_trace.get": "accounting.journal.read",
			"accounting.exceptions.list": "accounting.exception.read",
		},
	},
	moduleDependencies: {
		required: [],
	},
	optionalIntegratesWith: [
		{ moduleId: "sales", style: "events" },
		{ moduleId: "purchasing", style: "events" },
		{ moduleId: "inventory", style: "events" },
		{ moduleId: "receivables", style: "events" },
		{ moduleId: "payables", style: "events" },
		{ moduleId: "payments", style: "events" },
	],
} as const satisfies AfendaModuleManifest;
