/**
 * Human Resources semantic error codes — package authority.
 * Platform `Result` uses `@afenda/errors` ErrorCode; attach these via details.humanResourcesCode.
 */

export const HUMAN_RESOURCES_ERROR_INVALID_INPUT =
	"human_resources.invalid_input" as const;
export const HUMAN_RESOURCES_ERROR_UNAUTHORIZED =
	"human_resources.unauthorized" as const;
export const HUMAN_RESOURCES_ERROR_FORBIDDEN =
	"human_resources.forbidden" as const;
export const HUMAN_RESOURCES_ERROR_NOT_FOUND =
	"human_resources.not_found" as const;
export const HUMAN_RESOURCES_ERROR_CONFLICT =
	"human_resources.conflict" as const;
export const HUMAN_RESOURCES_ERROR_DUPLICATE =
	"human_resources.duplicate" as const;
export const HUMAN_RESOURCES_ERROR_INVALID_STATE_TRANSITION =
	"human_resources.invalid_state_transition" as const;
export const HUMAN_RESOURCES_ERROR_STALE_VERSION =
	"human_resources.stale_version" as const;
export const HUMAN_RESOURCES_ERROR_CROSS_ORGANIZATION_REFERENCE =
	"human_resources.cross_organization_reference" as const;
export const HUMAN_RESOURCES_ERROR_DEPENDENCY_UNAVAILABLE =
	"human_resources.dependency_unavailable" as const;
export const HUMAN_RESOURCES_ERROR_PERSISTENCE_FAILURE =
	"human_resources.persistence_failure" as const;

export const HUMAN_RESOURCES_ERROR_CODES = {
	INVALID_INPUT: HUMAN_RESOURCES_ERROR_INVALID_INPUT,
	UNAUTHORIZED: HUMAN_RESOURCES_ERROR_UNAUTHORIZED,
	FORBIDDEN: HUMAN_RESOURCES_ERROR_FORBIDDEN,
	NOT_FOUND: HUMAN_RESOURCES_ERROR_NOT_FOUND,
	CONFLICT: HUMAN_RESOURCES_ERROR_CONFLICT,
	DUPLICATE: HUMAN_RESOURCES_ERROR_DUPLICATE,
	INVALID_STATE_TRANSITION: HUMAN_RESOURCES_ERROR_INVALID_STATE_TRANSITION,
	STALE_VERSION: HUMAN_RESOURCES_ERROR_STALE_VERSION,
	CROSS_ORGANIZATION_REFERENCE:
		HUMAN_RESOURCES_ERROR_CROSS_ORGANIZATION_REFERENCE,
	DEPENDENCY_UNAVAILABLE: HUMAN_RESOURCES_ERROR_DEPENDENCY_UNAVAILABLE,
	PERSISTENCE_FAILURE: HUMAN_RESOURCES_ERROR_PERSISTENCE_FAILURE,
} as const;

export const HUMAN_RESOURCES_ERROR_CODE_LIST = [
	HUMAN_RESOURCES_ERROR_INVALID_INPUT,
	HUMAN_RESOURCES_ERROR_UNAUTHORIZED,
	HUMAN_RESOURCES_ERROR_FORBIDDEN,
	HUMAN_RESOURCES_ERROR_NOT_FOUND,
	HUMAN_RESOURCES_ERROR_CONFLICT,
	HUMAN_RESOURCES_ERROR_DUPLICATE,
	HUMAN_RESOURCES_ERROR_INVALID_STATE_TRANSITION,
	HUMAN_RESOURCES_ERROR_STALE_VERSION,
	HUMAN_RESOURCES_ERROR_CROSS_ORGANIZATION_REFERENCE,
	HUMAN_RESOURCES_ERROR_DEPENDENCY_UNAVAILABLE,
	HUMAN_RESOURCES_ERROR_PERSISTENCE_FAILURE,
] as const;

export type HumanResourcesErrorCode =
	(typeof HUMAN_RESOURCES_ERROR_CODE_LIST)[number];

export function humanResourcesErrorDetails(
	humanResourcesCode: HumanResourcesErrorCode,
): { humanResourcesCode: HumanResourcesErrorCode } {
	return { humanResourcesCode };
}
