import type { AfendaModuleManifest } from "@afenda/db/module-manifest";
import {
	HUMAN_RESOURCES_BENEFIT_ENROLLMENT_CHANGED_EVENT,
	HUMAN_RESOURCES_CERTIFICATION_EXPIRING_EVENT,
	HUMAN_RESOURCES_COMPENSATION_CHANGED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_CREATED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_TERMINATED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_TRANSFERRED_EVENT,
	HUMAN_RESOURCES_EMPLOYMENT_CHANGED_EVENT,
	HUMAN_RESOURCES_EMPLOYMENT_STARTED_EVENT,
	HUMAN_RESOURCES_LEAVE_APPROVED_EVENT,
	HUMAN_RESOURCES_OFFBOARDING_COMPLETED_EVENT,
	HUMAN_RESOURCES_OFFBOARDING_STARTED_EVENT,
	HUMAN_RESOURCES_OFFER_ACCEPTED_EVENT,
	HUMAN_RESOURCES_ONBOARDING_COMPLETED_EVENT,
	HUMAN_RESOURCES_ONBOARDING_STARTED_EVENT,
	HUMAN_RESOURCES_REQUISITION_APPROVED_EVENT,
	HUMAN_RESOURCES_TIMESHEET_APPROVED_EVENT,
} from "@afenda/events/schemas";

import {
	HUMAN_RESOURCES_COMMAND_APPLICATION_CREATE,
	HUMAN_RESOURCES_COMMAND_APPLICATION_MOVE_TO_IN_REVIEW,
	HUMAN_RESOURCES_COMMAND_APPLICATION_MOVE_TO_INTERVIEWING,
	HUMAN_RESOURCES_COMMAND_APPLICATION_REJECT,
	HUMAN_RESOURCES_COMMAND_APPLICATION_WITHDRAW,
	HUMAN_RESOURCES_COMMAND_ASSIGNMENT_CREATE,
	HUMAN_RESOURCES_COMMAND_ASSIGNMENT_END,
	HUMAN_RESOURCES_COMMAND_CANDIDATE_CREATE,
	HUMAN_RESOURCES_COMMAND_CANDIDATE_UPDATE_PROFILE,
	HUMAN_RESOURCES_COMMAND_DEPARTMENT_ACTIVATE,
	HUMAN_RESOURCES_COMMAND_DEPARTMENT_ARCHIVE,
	HUMAN_RESOURCES_COMMAND_DEPARTMENT_CREATE,
	HUMAN_RESOURCES_COMMAND_DEPARTMENT_UPDATE,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CREATE,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_UPDATE,
	HUMAN_RESOURCES_COMMAND_EMPLOYMENT_AMEND,
	HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CONTRACT_CREATE,
	HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CREATE,
	HUMAN_RESOURCES_COMMAND_IDS,
	HUMAN_RESOURCES_COMMAND_INTERVIEW_CANCEL,
	HUMAN_RESOURCES_COMMAND_INTERVIEW_RECORD_EVALUATION,
	HUMAN_RESOURCES_COMMAND_INTERVIEW_SCHEDULE,
	HUMAN_RESOURCES_COMMAND_JOB_ACTIVATE,
	HUMAN_RESOURCES_COMMAND_JOB_ARCHIVE,
	HUMAN_RESOURCES_COMMAND_JOB_CREATE,
	HUMAN_RESOURCES_COMMAND_JOB_UPDATE,
	HUMAN_RESOURCES_COMMAND_OFFER_ACCEPT,
	HUMAN_RESOURCES_COMMAND_OFFER_AMEND_DRAFT,
	HUMAN_RESOURCES_COMMAND_OFFER_CREATE,
	HUMAN_RESOURCES_COMMAND_OFFER_DECLINE,
	HUMAN_RESOURCES_COMMAND_OFFER_EXPIRE,
	HUMAN_RESOURCES_COMMAND_OFFER_ISSUE,
	HUMAN_RESOURCES_COMMAND_OFFER_WITHDRAW,
	HUMAN_RESOURCES_COMMAND_POSITION_ACTIVATE,
	HUMAN_RESOURCES_COMMAND_POSITION_CLOSE,
	HUMAN_RESOURCES_COMMAND_POSITION_CREATE,
	HUMAN_RESOURCES_COMMAND_POSITION_FREEZE,
	HUMAN_RESOURCES_COMMAND_POSITION_UPDATE,
	HUMAN_RESOURCES_COMMAND_REPORTING_LINE_ASSIGN_PRIMARY,
	HUMAN_RESOURCES_COMMAND_REPORTING_LINE_CLOSE,
	HUMAN_RESOURCES_COMMAND_REPORTING_LINE_REPLACE_PRIMARY,
	HUMAN_RESOURCES_COMMAND_REQUISITION_AMEND,
	HUMAN_RESOURCES_COMMAND_REQUISITION_APPROVE,
	HUMAN_RESOURCES_COMMAND_REQUISITION_CANCEL,
	HUMAN_RESOURCES_COMMAND_REQUISITION_CLOSE,
	HUMAN_RESOURCES_COMMAND_REQUISITION_CREATE_DRAFT,
	HUMAN_RESOURCES_COMMAND_REQUISITION_OPEN,
	HUMAN_RESOURCES_COMMAND_REQUISITION_PLACE_ON_HOLD,
	HUMAN_RESOURCES_COMMAND_REQUISITION_SUBMIT,
	HUMAN_RESOURCES_QUERY_APPLICATION_GET,
	HUMAN_RESOURCES_QUERY_APPLICATION_LIST,
	HUMAN_RESOURCES_QUERY_ASSIGNMENT_GET,
	HUMAN_RESOURCES_QUERY_CANDIDATE_GET,
	HUMAN_RESOURCES_QUERY_CANDIDATE_LIST,
	HUMAN_RESOURCES_QUERY_DEPARTMENT_GET,
	HUMAN_RESOURCES_QUERY_DEPARTMENT_LIST,
	HUMAN_RESOURCES_QUERY_EMPLOYEE_GET,
	HUMAN_RESOURCES_QUERY_EMPLOYEE_LIST,
	HUMAN_RESOURCES_QUERY_EMPLOYMENT_CONTRACT_GET,
	HUMAN_RESOURCES_QUERY_EMPLOYMENT_GET,
	HUMAN_RESOURCES_QUERY_IDS,
	HUMAN_RESOURCES_QUERY_INTERVIEW_EVALUATION_GET,
	HUMAN_RESOURCES_QUERY_INTERVIEW_GET,
	HUMAN_RESOURCES_QUERY_INTERVIEW_LIST,
	HUMAN_RESOURCES_QUERY_JOB_GET,
	HUMAN_RESOURCES_QUERY_JOB_LIST,
	HUMAN_RESOURCES_QUERY_OFFER_GET,
	HUMAN_RESOURCES_QUERY_OFFER_LIST,
	HUMAN_RESOURCES_QUERY_ORGANIZATION_TREE,
	HUMAN_RESOURCES_QUERY_POSITION_GET,
	HUMAN_RESOURCES_QUERY_POSITION_LIST,
	HUMAN_RESOURCES_QUERY_REPORTING_LINE_LIST_DIRECT_REPORTS,
	HUMAN_RESOURCES_QUERY_REPORTING_LINE_RESOLVE_PRIMARY_MANAGER,
	HUMAN_RESOURCES_QUERY_REQUISITION_GET,
	HUMAN_RESOURCES_QUERY_REQUISITION_LIST,
} from "./module-ids";
import {
	HUMAN_RESOURCES_AGGREGATES,
	HUMAN_RESOURCES_MUTATION_TABLES,
} from "./mutation-tables";
import {
	HUMAN_RESOURCES_PERMISSION_CANDIDATE_MANAGE,
	HUMAN_RESOURCES_PERMISSION_CODES,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CREATE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_UPDATE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYMENT_MANAGE,
	HUMAN_RESOURCES_PERMISSION_INTERVIEW_RECORD,
	HUMAN_RESOURCES_PERMISSION_OFFER_APPROVE,
	HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
	HUMAN_RESOURCES_PERMISSION_ORGANIZATION_READ,
	HUMAN_RESOURCES_PERMISSION_REQUISITION_CREATE,
} from "./permissions";

export const humanResourcesModuleManifest = {
	id: "human-resources",
	category: "erp",
	packageName: "@afenda/human-resources",
	band: "R1-F",
	lifecycle: "scaffolded",
	activationMode: "organization_toggle",
	owns: {
		aggregates: [...HUMAN_RESOURCES_AGGREGATES],
		commandNamespace: "human-resources",
		commands: [...HUMAN_RESOURCES_COMMAND_IDS],
		queryNamespace: "human-resources",
		queries: [...HUMAN_RESOURCES_QUERY_IDS],
	},
	persistence: {
		schemaOwner: "@afenda/db",
		mutationTables: [...HUMAN_RESOURCES_MUTATION_TABLES],
	},
	events: {
		namespace: "human-resources",
		emits: [
			HUMAN_RESOURCES_EMPLOYEE_CREATED_EVENT,
			HUMAN_RESOURCES_EMPLOYMENT_STARTED_EVENT,
			HUMAN_RESOURCES_EMPLOYMENT_CHANGED_EVENT,
			HUMAN_RESOURCES_EMPLOYEE_TRANSFERRED_EVENT,
			HUMAN_RESOURCES_EMPLOYEE_TERMINATED_EVENT,
			HUMAN_RESOURCES_REQUISITION_APPROVED_EVENT,
			HUMAN_RESOURCES_OFFER_ACCEPTED_EVENT,
			HUMAN_RESOURCES_ONBOARDING_STARTED_EVENT,
			HUMAN_RESOURCES_ONBOARDING_COMPLETED_EVENT,
			HUMAN_RESOURCES_OFFBOARDING_STARTED_EVENT,
			HUMAN_RESOURCES_OFFBOARDING_COMPLETED_EVENT,
			HUMAN_RESOURCES_COMPENSATION_CHANGED_EVENT,
			HUMAN_RESOURCES_BENEFIT_ENROLLMENT_CHANGED_EVENT,
			HUMAN_RESOURCES_LEAVE_APPROVED_EVENT,
			HUMAN_RESOURCES_TIMESHEET_APPROVED_EVENT,
			HUMAN_RESOURCES_CERTIFICATION_EXPIRING_EVENT,
		],
		consumes: [],
	},
	permissions: {
		namespace: "human-resources",
		codes: [...HUMAN_RESOURCES_PERMISSION_CODES],
	},
	authorization: {
		commands: {
			[HUMAN_RESOURCES_COMMAND_EMPLOYEE_CREATE]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CREATE,
			[HUMAN_RESOURCES_COMMAND_EMPLOYEE_UPDATE]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYEE_UPDATE,
			[HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CREATE]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYMENT_MANAGE,
			[HUMAN_RESOURCES_COMMAND_EMPLOYMENT_AMEND]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYMENT_MANAGE,
			[HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CONTRACT_CREATE]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYMENT_MANAGE,
			[HUMAN_RESOURCES_COMMAND_DEPARTMENT_CREATE]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
			[HUMAN_RESOURCES_COMMAND_DEPARTMENT_UPDATE]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
			[HUMAN_RESOURCES_COMMAND_DEPARTMENT_ACTIVATE]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
			[HUMAN_RESOURCES_COMMAND_DEPARTMENT_ARCHIVE]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
			[HUMAN_RESOURCES_COMMAND_JOB_CREATE]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
			[HUMAN_RESOURCES_COMMAND_JOB_UPDATE]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
			[HUMAN_RESOURCES_COMMAND_JOB_ACTIVATE]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
			[HUMAN_RESOURCES_COMMAND_JOB_ARCHIVE]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
			[HUMAN_RESOURCES_COMMAND_POSITION_CREATE]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
			[HUMAN_RESOURCES_COMMAND_POSITION_UPDATE]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
			[HUMAN_RESOURCES_COMMAND_POSITION_ACTIVATE]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
			[HUMAN_RESOURCES_COMMAND_POSITION_FREEZE]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
			[HUMAN_RESOURCES_COMMAND_POSITION_CLOSE]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
			[HUMAN_RESOURCES_COMMAND_ASSIGNMENT_CREATE]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYMENT_MANAGE,
			[HUMAN_RESOURCES_COMMAND_ASSIGNMENT_END]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYMENT_MANAGE,
			[HUMAN_RESOURCES_COMMAND_REPORTING_LINE_ASSIGN_PRIMARY]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
			[HUMAN_RESOURCES_COMMAND_REPORTING_LINE_CLOSE]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
			[HUMAN_RESOURCES_COMMAND_REPORTING_LINE_REPLACE_PRIMARY]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
			[HUMAN_RESOURCES_COMMAND_REQUISITION_CREATE_DRAFT]:
				HUMAN_RESOURCES_PERMISSION_REQUISITION_CREATE,
			[HUMAN_RESOURCES_COMMAND_REQUISITION_AMEND]:
				HUMAN_RESOURCES_PERMISSION_REQUISITION_CREATE,
			[HUMAN_RESOURCES_COMMAND_REQUISITION_SUBMIT]:
				HUMAN_RESOURCES_PERMISSION_REQUISITION_CREATE,
			[HUMAN_RESOURCES_COMMAND_REQUISITION_APPROVE]:
				HUMAN_RESOURCES_PERMISSION_REQUISITION_CREATE,
			[HUMAN_RESOURCES_COMMAND_REQUISITION_OPEN]:
				HUMAN_RESOURCES_PERMISSION_REQUISITION_CREATE,
			[HUMAN_RESOURCES_COMMAND_REQUISITION_PLACE_ON_HOLD]:
				HUMAN_RESOURCES_PERMISSION_REQUISITION_CREATE,
			[HUMAN_RESOURCES_COMMAND_REQUISITION_CLOSE]:
				HUMAN_RESOURCES_PERMISSION_REQUISITION_CREATE,
			[HUMAN_RESOURCES_COMMAND_REQUISITION_CANCEL]:
				HUMAN_RESOURCES_PERMISSION_REQUISITION_CREATE,
			[HUMAN_RESOURCES_COMMAND_CANDIDATE_CREATE]:
				HUMAN_RESOURCES_PERMISSION_CANDIDATE_MANAGE,
			[HUMAN_RESOURCES_COMMAND_CANDIDATE_UPDATE_PROFILE]:
				HUMAN_RESOURCES_PERMISSION_CANDIDATE_MANAGE,
			[HUMAN_RESOURCES_COMMAND_APPLICATION_CREATE]:
				HUMAN_RESOURCES_PERMISSION_CANDIDATE_MANAGE,
			[HUMAN_RESOURCES_COMMAND_APPLICATION_MOVE_TO_IN_REVIEW]:
				HUMAN_RESOURCES_PERMISSION_CANDIDATE_MANAGE,
			[HUMAN_RESOURCES_COMMAND_APPLICATION_MOVE_TO_INTERVIEWING]:
				HUMAN_RESOURCES_PERMISSION_CANDIDATE_MANAGE,
			[HUMAN_RESOURCES_COMMAND_APPLICATION_REJECT]:
				HUMAN_RESOURCES_PERMISSION_CANDIDATE_MANAGE,
			[HUMAN_RESOURCES_COMMAND_APPLICATION_WITHDRAW]:
				HUMAN_RESOURCES_PERMISSION_CANDIDATE_MANAGE,
			[HUMAN_RESOURCES_COMMAND_INTERVIEW_SCHEDULE]:
				HUMAN_RESOURCES_PERMISSION_INTERVIEW_RECORD,
			[HUMAN_RESOURCES_COMMAND_INTERVIEW_CANCEL]:
				HUMAN_RESOURCES_PERMISSION_INTERVIEW_RECORD,
			[HUMAN_RESOURCES_COMMAND_INTERVIEW_RECORD_EVALUATION]:
				HUMAN_RESOURCES_PERMISSION_INTERVIEW_RECORD,
			[HUMAN_RESOURCES_COMMAND_OFFER_CREATE]:
				HUMAN_RESOURCES_PERMISSION_OFFER_APPROVE,
			[HUMAN_RESOURCES_COMMAND_OFFER_AMEND_DRAFT]:
				HUMAN_RESOURCES_PERMISSION_OFFER_APPROVE,
			[HUMAN_RESOURCES_COMMAND_OFFER_ISSUE]:
				HUMAN_RESOURCES_PERMISSION_OFFER_APPROVE,
			[HUMAN_RESOURCES_COMMAND_OFFER_ACCEPT]:
				HUMAN_RESOURCES_PERMISSION_OFFER_APPROVE,
			[HUMAN_RESOURCES_COMMAND_OFFER_DECLINE]:
				HUMAN_RESOURCES_PERMISSION_OFFER_APPROVE,
			[HUMAN_RESOURCES_COMMAND_OFFER_EXPIRE]:
				HUMAN_RESOURCES_PERMISSION_OFFER_APPROVE,
			[HUMAN_RESOURCES_COMMAND_OFFER_WITHDRAW]:
				HUMAN_RESOURCES_PERMISSION_OFFER_APPROVE,
		},
		queries: {
			[HUMAN_RESOURCES_QUERY_EMPLOYEE_GET]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ,
			[HUMAN_RESOURCES_QUERY_EMPLOYEE_LIST]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ,
			[HUMAN_RESOURCES_QUERY_EMPLOYMENT_GET]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ,
			[HUMAN_RESOURCES_QUERY_EMPLOYMENT_CONTRACT_GET]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ,
			[HUMAN_RESOURCES_QUERY_DEPARTMENT_GET]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_READ,
			[HUMAN_RESOURCES_QUERY_DEPARTMENT_LIST]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_READ,
			[HUMAN_RESOURCES_QUERY_JOB_GET]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_READ,
			[HUMAN_RESOURCES_QUERY_JOB_LIST]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_READ,
			[HUMAN_RESOURCES_QUERY_POSITION_GET]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_READ,
			[HUMAN_RESOURCES_QUERY_POSITION_LIST]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_READ,
			[HUMAN_RESOURCES_QUERY_ASSIGNMENT_GET]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ,
			[HUMAN_RESOURCES_QUERY_REPORTING_LINE_RESOLVE_PRIMARY_MANAGER]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_READ,
			[HUMAN_RESOURCES_QUERY_REPORTING_LINE_LIST_DIRECT_REPORTS]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_READ,
			[HUMAN_RESOURCES_QUERY_ORGANIZATION_TREE]:
				HUMAN_RESOURCES_PERMISSION_ORGANIZATION_READ,
			[HUMAN_RESOURCES_QUERY_REQUISITION_GET]:
				HUMAN_RESOURCES_PERMISSION_REQUISITION_CREATE,
			[HUMAN_RESOURCES_QUERY_REQUISITION_LIST]:
				HUMAN_RESOURCES_PERMISSION_REQUISITION_CREATE,
			[HUMAN_RESOURCES_QUERY_CANDIDATE_GET]:
				HUMAN_RESOURCES_PERMISSION_CANDIDATE_MANAGE,
			[HUMAN_RESOURCES_QUERY_CANDIDATE_LIST]:
				HUMAN_RESOURCES_PERMISSION_CANDIDATE_MANAGE,
			[HUMAN_RESOURCES_QUERY_APPLICATION_GET]:
				HUMAN_RESOURCES_PERMISSION_CANDIDATE_MANAGE,
			[HUMAN_RESOURCES_QUERY_APPLICATION_LIST]:
				HUMAN_RESOURCES_PERMISSION_CANDIDATE_MANAGE,
			[HUMAN_RESOURCES_QUERY_INTERVIEW_GET]:
				HUMAN_RESOURCES_PERMISSION_INTERVIEW_RECORD,
			[HUMAN_RESOURCES_QUERY_INTERVIEW_LIST]:
				HUMAN_RESOURCES_PERMISSION_INTERVIEW_RECORD,
			[HUMAN_RESOURCES_QUERY_INTERVIEW_EVALUATION_GET]:
				HUMAN_RESOURCES_PERMISSION_INTERVIEW_RECORD,
			[HUMAN_RESOURCES_QUERY_OFFER_GET]:
				HUMAN_RESOURCES_PERMISSION_OFFER_APPROVE,
			[HUMAN_RESOURCES_QUERY_OFFER_LIST]:
				HUMAN_RESOURCES_PERMISSION_OFFER_APPROVE,
		},
	},
	moduleDependencies: {
		required: ["master-data"],
	},
	optionalIntegratesWith: [
		{ moduleId: "payroll", style: "events" },
		{ moduleId: "payments", style: "events" },
		{ moduleId: "accounting", style: "events" },
	],
} as const satisfies AfendaModuleManifest;
