import type { AfendaModuleManifest } from "@afenda/db/module-manifest";
import {
	HUMAN_RESOURCES_BENEFIT_ENROLLMENT_CHANGED_EVENT,
	HUMAN_RESOURCES_CERTIFICATION_EXPIRING_EVENT,
	HUMAN_RESOURCES_COMPENSATION_CHANGED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_CREATED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_TERMINATED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_TRANSFERRED_EVENT,
	HUMAN_RESOURCES_EMPLOYMENT_CHANGED_EVENT,
	HUMAN_RESOURCES_EMPLOYMENT_STARTED_EVENT,
	HUMAN_RESOURCES_LEAVE_APPROVED_EVENT,
	HUMAN_RESOURCES_OFFBOARDING_COMPLETED_EVENT,
	HUMAN_RESOURCES_OFFBOARDING_STARTED_EVENT,
	HUMAN_RESOURCES_OFFER_ACCEPTED_EVENT,
	HUMAN_RESOURCES_ONBOARDING_COMPLETED_EVENT,
	HUMAN_RESOURCES_ONBOARDING_STARTED_EVENT,
	HUMAN_RESOURCES_REQUISITION_APPROVED_EVENT,
	HUMAN_RESOURCES_TIMESHEET_APPROVED_EVENT,
} from "@afenda/events/schemas";

import {
	HUMAN_RESOURCES_COMMAND_ASSIGNMENT_CREATE,
	HUMAN_RESOURCES_COMMAND_ASSIGNMENT_END,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CREATE,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_UPDATE,
	HUMAN_RESOURCES_COMMAND_EMPLOYMENT_AMEND,
	HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CONTRACT_CREATE,
	HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CREATE,
	HUMAN_RESOURCES_COMMAND_IDS,
	HUMAN_RESOURCES_COMMAND_POSITION_CREATE,
	HUMAN_RESOURCES_QUERY_ASSIGNMENT_GET,
	HUMAN_RESOURCES_QUERY_EMPLOYEE_GET,
	HUMAN_RESOURCES_QUERY_EMPLOYEE_LIST,
	HUMAN_RESOURCES_QUERY_EMPLOYMENT_CONTRACT_GET,
	HUMAN_RESOURCES_QUERY_EMPLOYMENT_GET,
	HUMAN_RESOURCES_QUERY_IDS,
	HUMAN_RESOURCES_QUERY_POSITION_GET,
	HUMAN_RESOURCES_QUERY_POSITION_LIST,
} from "./module-ids";
import {
	HUMAN_RESOURCES_AGGREGATES,
	HUMAN_RESOURCES_MUTATION_TABLES,
} from "./mutation-tables";
import {
	HUMAN_RESOURCES_PERMISSION_CODES,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CREATE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_UPDATE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYMENT_MANAGE,
} from "./permissions";

export const humanResourcesModuleManifest = {
	id: "human-resources",
	category: "erp",
	packageName: "@afenda/human-resources",
	band: "R1-F",
	lifecycle: "scaffolded",
	activationMode: "organization_toggle",
	owns: {
		aggregates: [...HUMAN_RESOURCES_AGGREGATES],
		commandNamespace: "human-resources",
		commands: [...HUMAN_RESOURCES_COMMAND_IDS],
		queryNamespace: "human-resources",
		queries: [...HUMAN_RESOURCES_QUERY_IDS],
	},
	persistence: {
		schemaOwner: "@afenda/db",
		mutationTables: [...HUMAN_RESOURCES_MUTATION_TABLES],
	},
	events: {
		namespace: "human-resources",
		emits: [
			HUMAN_RESOURCES_EMPLOYEE_CREATED_EVENT,
			HUMAN_RESOURCES_EMPLOYMENT_STARTED_EVENT,
			HUMAN_RESOURCES_EMPLOYMENT_CHANGED_EVENT,
			HUMAN_RESOURCES_EMPLOYEE_TRANSFERRED_EVENT,
			HUMAN_RESOURCES_EMPLOYEE_TERMINATED_EVENT,
			HUMAN_RESOURCES_REQUISITION_APPROVED_EVENT,
			HUMAN_RESOURCES_OFFER_ACCEPTED_EVENT,
			HUMAN_RESOURCES_ONBOARDING_STARTED_EVENT,
			HUMAN_RESOURCES_ONBOARDING_COMPLETED_EVENT,
			HUMAN_RESOURCES_OFFBOARDING_STARTED_EVENT,
			HUMAN_RESOURCES_OFFBOARDING_COMPLETED_EVENT,
			HUMAN_RESOURCES_COMPENSATION_CHANGED_EVENT,
			HUMAN_RESOURCES_BENEFIT_ENROLLMENT_CHANGED_EVENT,
			HUMAN_RESOURCES_LEAVE_APPROVED_EVENT,
			HUMAN_RESOURCES_TIMESHEET_APPROVED_EVENT,
			HUMAN_RESOURCES_CERTIFICATION_EXPIRING_EVENT,
		],
		consumes: [],
	},
	permissions: {
		namespace: "human-resources",
		codes: [...HUMAN_RESOURCES_PERMISSION_CODES],
	},
	authorization: {
		commands: {
			[HUMAN_RESOURCES_COMMAND_EMPLOYEE_CREATE]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CREATE,
			[HUMAN_RESOURCES_COMMAND_EMPLOYEE_UPDATE]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYEE_UPDATE,
			[HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CREATE]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYMENT_MANAGE,
			[HUMAN_RESOURCES_COMMAND_EMPLOYMENT_AMEND]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYMENT_MANAGE,
			[HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CONTRACT_CREATE]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYMENT_MANAGE,
			[HUMAN_RESOURCES_COMMAND_POSITION_CREATE]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYMENT_MANAGE,
			[HUMAN_RESOURCES_COMMAND_ASSIGNMENT_CREATE]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYMENT_MANAGE,
			[HUMAN_RESOURCES_COMMAND_ASSIGNMENT_END]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYMENT_MANAGE,
		},
		queries: {
			[HUMAN_RESOURCES_QUERY_EMPLOYEE_GET]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ,
			[HUMAN_RESOURCES_QUERY_EMPLOYEE_LIST]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ,
			[HUMAN_RESOURCES_QUERY_EMPLOYMENT_GET]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ,
			[HUMAN_RESOURCES_QUERY_EMPLOYMENT_CONTRACT_GET]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ,
			[HUMAN_RESOURCES_QUERY_POSITION_GET]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ,
			[HUMAN_RESOURCES_QUERY_POSITION_LIST]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ,
			[HUMAN_RESOURCES_QUERY_ASSIGNMENT_GET]:
				HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ,
		},
	},
	moduleDependencies: {
		required: ["master-data"],
	},
	optionalIntegratesWith: [
		{ moduleId: "payroll", style: "events" },
		{ moduleId: "payments", style: "events" },
		{ moduleId: "accounting", style: "events" },
	],
} as const satisfies AfendaModuleManifest;
