import type { HumanResourcesEventType } from "@afenda/events";
import {
	HUMAN_RESOURCES_EMPLOYEE_CREATED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_NEARING_EXPIRY_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_REGISTERED_EVENT,
	HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_VERIFIED_EVENT,
	HUMAN_RESOURCES_LEARNING_COMPLETION_RECORDED_EVENT,
	HUMAN_RESOURCES_POLICY_ACKNOWLEDGEMENT_ACKNOWLEDGED_EVENT,
	HUMAN_RESOURCES_POLICY_ACKNOWLEDGEMENT_OUTSTANDING_EVENT,
	HUMAN_RESOURCES_TIME_ATTENDANCE_CORRECTED_EVENT,
	HUMAN_RESOURCES_TIME_ATTENDANCE_RECORDED_EVENT,
	HUMAN_RESOURCES_TIME_EXCEPTION_CREATED_EVENT,
	HUMAN_RESOURCES_TIME_OVERTIME_APPROVED_EVENT,
	HUMAN_RESOURCES_TIME_PAYROLL_HANDOFF_READY_EVENT,
	HUMAN_RESOURCES_TIME_SCHEDULE_PUBLISHED_EVENT,
	HUMAN_RESOURCES_TIME_TIMESHEET_APPROVAL_STEP_RECORDED_EVENT,
	HUMAN_RESOURCES_TIME_TIMESHEET_LOCKED_EVENT,
	HUMAN_RESOURCES_TIME_TIMESHEET_REOPENED_EVENT,
	HUMAN_RESOURCES_TIME_TIMESHEET_SUBMITTED_EVENT,
	HUMAN_RESOURCES_TIMESHEET_APPROVED_EVENT,
	HUMAN_RESOURCES_WORK_ELIGIBILITY_SUSPENDED_EVENT,
} from "@afenda/events/schemas";

import {
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_BREAK_WAIVER_APPROVE,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENT_CORRECT,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENT_RECORD,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENT_VOID,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENTS_IMPORT,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_CREATE,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_EXCUSE,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_REJECT,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_RESOLVE,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_REVIEW,
	HUMAN_RESOURCES_COMMAND_ATTENDANCE_SESSION_RESOLVE,
	HUMAN_RESOURCES_COMMAND_CERTIFICATION_EXPIRE,
	HUMAN_RESOURCES_COMMAND_CERTIFICATION_ISSUE,
	HUMAN_RESOURCES_COMMAND_CERTIFICATION_REVOKE,
	HUMAN_RESOURCES_COMMAND_COMPLETION_RECORD,
	HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_CREATE,
	HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_PUBLISH,
	HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_RETIRE,
	HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_UPDATE,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_CREATE,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_MARK_EXPIRED,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REGISTER,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REJECT,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REVOKE_VERIFICATION,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_UPDATE_METADATA,
	HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_VERIFY,
	HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CALENDAR_ASSIGN,
	HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CALENDAR_END,
	HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_APPROVE,
	HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_CANCEL,
	HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_CREATE,
	HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_RECORD_ACTUAL,
	HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_REJECT,
	HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_VERIFY,
	HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_ACKNOWLEDGE,
	HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_ISSUE,
	HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_REVOKE,
	HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_SUPERSEDE,
	HUMAN_RESOURCES_COMMAND_SHIFT_ACTIVATE,
	HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGN,
	HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_CANCEL,
	HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_CHANGE,
	HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_COMPLETE,
	HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_PUBLISH,
	HUMAN_RESOURCES_COMMAND_SHIFT_BREAK_ADD,
	HUMAN_RESOURCES_COMMAND_SHIFT_BREAK_REMOVE,
	HUMAN_RESOURCES_COMMAND_SHIFT_CREATE,
	HUMAN_RESOURCES_COMMAND_SHIFT_DEACTIVATE,
	HUMAN_RESOURCES_COMMAND_SHIFT_SUPERSEDE,
	HUMAN_RESOURCES_COMMAND_SHIFT_UPDATE,
	HUMAN_RESOURCES_COMMAND_TIME_APPROVAL_AUTHORITY_ASSIGN,
	HUMAN_RESOURCES_COMMAND_TIME_APPROVAL_AUTHORITY_END,
	HUMAN_RESOURCES_COMMAND_TIME_POLICY_ACTIVATE,
	HUMAN_RESOURCES_COMMAND_TIME_POLICY_ASSIGN,
	HUMAN_RESOURCES_COMMAND_TIME_POLICY_CREATE,
	HUMAN_RESOURCES_COMMAND_TIME_POLICY_SUPERSEDE,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_APPROVE,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_CREATE,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_ENTRY_ADD,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_ENTRY_REMOVE,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_ENTRY_UPDATE,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_GENERATE_ENTRIES,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_LOCK,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_REJECT,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_REOPEN,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_RETURN,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_SUBMIT,
	HUMAN_RESOURCES_COMMAND_TIMESHEET_SUPERSEDE,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_ARCHIVE,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_CREATE,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_DATE_OVERRIDE_ADD,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_DATE_OVERRIDE_REMOVE,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_HOLIDAY_ADD,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_HOLIDAY_REMOVE,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_SCOPE_ASSIGN,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_SCOPE_END,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_SUPERSEDE,
	HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_UPDATE,
	HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_CLOSE,
	HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_RECORD,
	HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_RENEW,
	HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_SUSPEND,
	HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_VERIFY,
	type HumanResourcesCommandId,
} from "./module-ids";

export type MutationEmissionKind = "domain_event" | "audit_only" | "none";

export type MutationEmissionEntry = {
	command: HumanResourcesCommandId;
	emission: MutationEmissionKind;
	/** Domain event type(s) emitted on the happy path (may be conditional). */
	eventTypes?: readonly HumanResourcesEventType[];
};

/**
 * Documents which mutation commands emit external domain events vs audit-only.
 * Expand as additional command fixtures are added to correlation-integrity tests.
 */
export const HUMAN_RESOURCES_MUTATION_EMISSION_REGISTRY = [
	{
		command: HUMAN_RESOURCES_COMMAND_EMPLOYEE_CREATE,
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_EMPLOYEE_CREATED_EVENT],
	},
	{
		command: HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_CREATE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_UPDATE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_PUBLISH,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_DOCUMENT_REQUIREMENT_RETIRE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REGISTER,
		emission: "domain_event",
		eventTypes: [
			HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_REGISTERED_EVENT,
			HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_NEARING_EXPIRY_EVENT,
		],
	},
	{
		command: HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_UPDATE_METADATA,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_VERIFY,
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_EMPLOYEE_DOCUMENT_VERIFIED_EVENT],
	},
	{
		command: HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REJECT,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_REVOKE_VERIFICATION,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_EMPLOYEE_DOCUMENT_MARK_EXPIRED,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_RECORD,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_VERIFY,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_SUSPEND,
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_WORK_ELIGIBILITY_SUSPENDED_EVENT],
	},
	{
		command: HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_RENEW,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_WORK_ELIGIBILITY_CLOSE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_ISSUE,
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_POLICY_ACKNOWLEDGEMENT_OUTSTANDING_EVENT],
	},
	{
		command: HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_ACKNOWLEDGE,
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_POLICY_ACKNOWLEDGEMENT_ACKNOWLEDGED_EVENT],
	},
	{
		command: HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_REVOKE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_POLICY_ACKNOWLEDGEMENT_SUPERSEDE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_CERTIFICATION_ISSUE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_CERTIFICATION_EXPIRE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_CERTIFICATION_REVOKE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_COMPLETION_RECORD,
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_LEARNING_COMPLETION_RECORDED_EVENT],
	},
	// --- Time domain (all 47 mutation commands) ---
	{
		command: HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_CREATE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_SUPERSEDE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_UPDATE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_ARCHIVE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_HOLIDAY_ADD,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_HOLIDAY_REMOVE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_DATE_OVERRIDE_ADD,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_DATE_OVERRIDE_REMOVE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CALENDAR_ASSIGN,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_EMPLOYMENT_CALENDAR_END,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_SCOPE_ASSIGN,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_WORK_CALENDAR_SCOPE_END,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_TIME_POLICY_CREATE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_TIME_POLICY_ACTIVATE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_TIME_POLICY_SUPERSEDE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_TIME_POLICY_ASSIGN,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_TIME_APPROVAL_AUTHORITY_ASSIGN,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_TIME_APPROVAL_AUTHORITY_END,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_SHIFT_CREATE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_SHIFT_SUPERSEDE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_SHIFT_UPDATE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_SHIFT_ACTIVATE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_SHIFT_DEACTIVATE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_SHIFT_BREAK_ADD,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_SHIFT_BREAK_REMOVE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGN,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_PUBLISH,
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_TIME_SCHEDULE_PUBLISHED_EVENT],
	},
	{
		command: HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_CANCEL,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_CHANGE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_SHIFT_ASSIGNMENT_COMPLETE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENT_RECORD,
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_TIME_ATTENDANCE_RECORDED_EVENT],
	},
	{
		// Import emits batch audit in P0-05; domain_event wiring is owned by HR-TIME-P0-04.
		command: HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENTS_IMPORT,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENT_CORRECT,
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_TIME_ATTENDANCE_CORRECTED_EVENT],
	},
	{
		command: HUMAN_RESOURCES_COMMAND_ATTENDANCE_EVENT_VOID,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_ATTENDANCE_SESSION_RESOLVE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_ATTENDANCE_BREAK_WAIVER_APPROVE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_CREATE,
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_TIME_EXCEPTION_CREATED_EVENT],
	},
	{
		command: HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_REVIEW,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_EXCUSE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_REJECT,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_ATTENDANCE_EXCEPTION_RESOLVE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_TIMESHEET_CREATE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_TIMESHEET_GENERATE_ENTRIES,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_TIMESHEET_ENTRY_ADD,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_TIMESHEET_ENTRY_UPDATE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_TIMESHEET_ENTRY_REMOVE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_TIMESHEET_SUBMIT,
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_TIME_TIMESHEET_SUBMITTED_EVENT],
	},
	{
		command: HUMAN_RESOURCES_COMMAND_TIMESHEET_RETURN,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_TIMESHEET_APPROVE,
		emission: "domain_event",
		eventTypes: [
			HUMAN_RESOURCES_TIME_TIMESHEET_APPROVAL_STEP_RECORDED_EVENT,
			HUMAN_RESOURCES_TIMESHEET_APPROVED_EVENT,
		],
	},
	{
		command: HUMAN_RESOURCES_COMMAND_TIMESHEET_REJECT,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_TIMESHEET_REOPEN,
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_TIME_TIMESHEET_REOPENED_EVENT],
	},
	{
		command: HUMAN_RESOURCES_COMMAND_TIMESHEET_LOCK,
		emission: "domain_event",
		eventTypes: [
			HUMAN_RESOURCES_TIME_TIMESHEET_LOCKED_EVENT,
			HUMAN_RESOURCES_TIME_PAYROLL_HANDOFF_READY_EVENT,
		],
	},
	{
		command: HUMAN_RESOURCES_COMMAND_TIMESHEET_SUPERSEDE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_CREATE,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_APPROVE,
		emission: "domain_event",
		eventTypes: [HUMAN_RESOURCES_TIME_OVERTIME_APPROVED_EVENT],
	},
	{
		command: HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_REJECT,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_CANCEL,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_RECORD_ACTUAL,
		emission: "audit_only",
	},
	{
		command: HUMAN_RESOURCES_COMMAND_OVERTIME_REQUEST_VERIFY,
		emission: "audit_only",
	},
] as const satisfies readonly MutationEmissionEntry[];

export type RegisteredMutationCommand =
	(typeof HUMAN_RESOURCES_MUTATION_EMISSION_REGISTRY)[number]["command"];

export function getMutationEmissionEntry(
	command: HumanResourcesCommandId,
): MutationEmissionEntry | undefined {
	return HUMAN_RESOURCES_MUTATION_EMISSION_REGISTRY.find(
		(entry) => entry.command === command,
	);
}
