/**
 * Human Resources permission codes — ERP-owned; must stay aligned with
 * `@afenda/db` PLATFORM_PERMISSION_V1 (human-resources.*).
 */

export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CREATE =
	"human-resources.employee.create" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ =
	"human-resources.employee.read" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_UPDATE =
	"human-resources.employee.update" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYMENT_MANAGE =
	"human-resources.employment.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_ORGANIZATION_READ =
	"human-resources.organization.read" as const;
export const HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE =
	"human-resources.organization.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_REQUISITION_CREATE =
	"human-resources.requisition.create" as const;
export const HUMAN_RESOURCES_PERMISSION_CANDIDATE_MANAGE =
	"human-resources.candidate.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_INTERVIEW_RECORD =
	"human-resources.interview.record" as const;
export const HUMAN_RESOURCES_PERMISSION_OFFER_APPROVE =
	"human-resources.offer.approve" as const;
export const HUMAN_RESOURCES_PERMISSION_ONBOARDING_MANAGE =
	"human-resources.onboarding.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_OFFBOARDING_MANAGE =
	"human-resources.offboarding.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_LEAVE_POLICY_READ =
	"human-resources.leave-policy.read" as const;
export const HUMAN_RESOURCES_PERMISSION_LEAVE_POLICY_MANAGE =
	"human-resources.leave-policy.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_LEAVE_ENTITLEMENT_READ =
	"human-resources.leave-entitlement.read" as const;
export const HUMAN_RESOURCES_PERMISSION_LEAVE_ENTITLEMENT_GRANT =
	"human-resources.leave-entitlement.grant" as const;
export const HUMAN_RESOURCES_PERMISSION_LEAVE_ENTITLEMENT_ADJUST =
	"human-resources.leave-entitlement.adjust" as const;
export const HUMAN_RESOURCES_PERMISSION_LEAVE_REQUEST_OWN =
	"human-resources.leave-request.own" as const;
export const HUMAN_RESOURCES_PERMISSION_LEAVE_REQUEST_APPROVE_TEAM =
	"human-resources.leave-request.approve-team" as const;
export const HUMAN_RESOURCES_PERMISSION_LEAVE_REQUEST_BACKDATE =
	"human-resources.leave-request.backdate" as const;
export const HUMAN_RESOURCES_PERMISSION_LEAVE_REQUEST_SENSITIVE_READ =
	"human-resources.leave-request.sensitive-read" as const;
export const HUMAN_RESOURCES_PERMISSION_ATTENDANCE_MANAGE =
	"human-resources.attendance.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_TIMESHEET_APPROVE =
	"human-resources.timesheet.approve" as const;
export const HUMAN_RESOURCES_PERMISSION_PERFORMANCE_MANAGE =
	"human-resources.performance.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_PERFORMANCE_OWN_READ =
	"human-resources.performance.own.read" as const;
export const HUMAN_RESOURCES_PERMISSION_PERFORMANCE_MANAGER_MANAGE =
	"human-resources.performance.manager.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_PERFORMANCE_IMPROVEMENT_PLAN_MANAGE =
	"human-resources.performance.improvement-plan.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_PERFORMANCE_REVIEW_REOPEN =
	"human-resources.performance.review.reopen" as const;
export const HUMAN_RESOURCES_PERMISSION_PERFORMANCE_CONFIDENTIAL_READ =
	"human-resources.performance.confidential.read" as const;
export const HUMAN_RESOURCES_PERMISSION_LEARNING_MANAGE =
	"human-resources.learning.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_CERTIFICATION_MANAGE =
	"human-resources.certification.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_COMPENSATION_READ =
	"human-resources.compensation.read" as const;
export const HUMAN_RESOURCES_PERMISSION_COMPENSATION_MANAGE =
	"human-resources.compensation.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_BENEFITS_MANAGE =
	"human-resources.benefits.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_OPEN =
	"human-resources.employee-case.open" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_ASSIGNED_READ =
	"human-resources.employee-case.assigned.read" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_INVESTIGATE =
	"human-resources.employee-case.investigate" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_FINDING =
	"human-resources.employee-case.finding" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_ACTION_APPROVE =
	"human-resources.employee-case.action.approve" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_APPEAL =
	"human-resources.employee-case.appeal" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_EXCEPTIONAL_ADMIN =
	"human-resources.employee-case.exceptional.admin" as const;
export const HUMAN_RESOURCES_PERMISSION_WORKFORCE_PLAN_READ =
	"human-resources.workforce-plan.read" as const;
export const HUMAN_RESOURCES_PERMISSION_WORKFORCE_PLAN_PREPARE =
	"human-resources.workforce-plan.prepare" as const;
export const HUMAN_RESOURCES_PERMISSION_WORKFORCE_PLAN_APPROVE =
	"human-resources.workforce-plan.approve" as const;
export const HUMAN_RESOURCES_PERMISSION_HEADCOUNT_RESERVE =
	"human-resources.headcount.reserve" as const;
export const HUMAN_RESOURCES_PERMISSION_HEADCOUNT_EXCEPTIONAL_ADJUST =
	"human-resources.headcount.exceptional-adjust" as const;
export const HUMAN_RESOURCES_PERMISSION_DOCUMENT_REQUIREMENT_MANAGE =
	"human-resources.document-requirement.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_DOCUMENT_OWN_READ =
	"human-resources.employee-document.own.read" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_DOCUMENT_OWN_REGISTER =
	"human-resources.employee-document.own.register" as const;
export const HUMAN_RESOURCES_PERMISSION_EMPLOYEE_DOCUMENT_VERIFY =
	"human-resources.employee-document.verify" as const;
export const HUMAN_RESOURCES_PERMISSION_WORK_ELIGIBILITY_VERIFY =
	"human-resources.work-eligibility.verify" as const;
export const HUMAN_RESOURCES_PERMISSION_COMPLIANCE_ADMINISTER =
	"human-resources.compliance.administer" as const;
export const HUMAN_RESOURCES_PERMISSION_IDENTITY_DOCUMENT_SENSITIVE_READ =
	"human-resources.identity-document.sensitive.read" as const;
export const HUMAN_RESOURCES_PERMISSION_POLICY_ACKNOWLEDGEMENT_ADMINISTER =
	"human-resources.policy-acknowledgement.administer" as const;
export const HUMAN_RESOURCES_PERMISSION_COMPETENCY_READ =
	"human-resources.competency.read" as const;
export const HUMAN_RESOURCES_PERMISSION_COMPETENCY_MANAGE =
	"human-resources.competency.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_COMPETENCY_ASSESS =
	"human-resources.competency.assess" as const;
export const HUMAN_RESOURCES_PERMISSION_CAREER_PLAN_OWN_READ =
	"human-resources.career-plan.own.read" as const;
export const HUMAN_RESOURCES_PERMISSION_CAREER_PLAN_MANAGE =
	"human-resources.career-plan.manage" as const;
export const HUMAN_RESOURCES_PERMISSION_TALENT_ADMIN =
	"human-resources.talent.admin" as const;
export const HUMAN_RESOURCES_PERMISSION_TALENT_PROFILE_SENSITIVE_READ =
	"human-resources.talent.profile.sensitive.read" as const;
export const HUMAN_RESOURCES_PERMISSION_SUCCESSION_ADMIN =
	"human-resources.succession.admin" as const;
export const HUMAN_RESOURCES_PERMISSION_SUCCESSION_EXECUTIVE_READ =
	"human-resources.succession.executive.read" as const;

export const HUMAN_RESOURCES_PERMISSION_CODES = [
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CREATE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_READ,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_UPDATE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYMENT_MANAGE,
	HUMAN_RESOURCES_PERMISSION_ORGANIZATION_READ,
	HUMAN_RESOURCES_PERMISSION_ORGANIZATION_MANAGE,
	HUMAN_RESOURCES_PERMISSION_REQUISITION_CREATE,
	HUMAN_RESOURCES_PERMISSION_CANDIDATE_MANAGE,
	HUMAN_RESOURCES_PERMISSION_INTERVIEW_RECORD,
	HUMAN_RESOURCES_PERMISSION_OFFER_APPROVE,
	HUMAN_RESOURCES_PERMISSION_ONBOARDING_MANAGE,
	HUMAN_RESOURCES_PERMISSION_OFFBOARDING_MANAGE,
	HUMAN_RESOURCES_PERMISSION_LEAVE_POLICY_READ,
	HUMAN_RESOURCES_PERMISSION_LEAVE_POLICY_MANAGE,
	HUMAN_RESOURCES_PERMISSION_LEAVE_ENTITLEMENT_READ,
	HUMAN_RESOURCES_PERMISSION_LEAVE_ENTITLEMENT_GRANT,
	HUMAN_RESOURCES_PERMISSION_LEAVE_ENTITLEMENT_ADJUST,
	HUMAN_RESOURCES_PERMISSION_LEAVE_REQUEST_OWN,
	HUMAN_RESOURCES_PERMISSION_LEAVE_REQUEST_APPROVE_TEAM,
	HUMAN_RESOURCES_PERMISSION_LEAVE_REQUEST_BACKDATE,
	HUMAN_RESOURCES_PERMISSION_LEAVE_REQUEST_SENSITIVE_READ,
	HUMAN_RESOURCES_PERMISSION_ATTENDANCE_MANAGE,
	HUMAN_RESOURCES_PERMISSION_TIMESHEET_APPROVE,
	HUMAN_RESOURCES_PERMISSION_PERFORMANCE_MANAGE,
	HUMAN_RESOURCES_PERMISSION_PERFORMANCE_OWN_READ,
	HUMAN_RESOURCES_PERMISSION_PERFORMANCE_MANAGER_MANAGE,
	HUMAN_RESOURCES_PERMISSION_PERFORMANCE_IMPROVEMENT_PLAN_MANAGE,
	HUMAN_RESOURCES_PERMISSION_PERFORMANCE_REVIEW_REOPEN,
	HUMAN_RESOURCES_PERMISSION_PERFORMANCE_CONFIDENTIAL_READ,
	HUMAN_RESOURCES_PERMISSION_LEARNING_MANAGE,
	HUMAN_RESOURCES_PERMISSION_CERTIFICATION_MANAGE,
	HUMAN_RESOURCES_PERMISSION_COMPENSATION_READ,
	HUMAN_RESOURCES_PERMISSION_COMPENSATION_MANAGE,
	HUMAN_RESOURCES_PERMISSION_BENEFITS_MANAGE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_OPEN,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_ASSIGNED_READ,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_INVESTIGATE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_FINDING,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_ACTION_APPROVE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_APPEAL,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_CASE_EXCEPTIONAL_ADMIN,
	HUMAN_RESOURCES_PERMISSION_WORKFORCE_PLAN_READ,
	HUMAN_RESOURCES_PERMISSION_WORKFORCE_PLAN_PREPARE,
	HUMAN_RESOURCES_PERMISSION_WORKFORCE_PLAN_APPROVE,
	HUMAN_RESOURCES_PERMISSION_HEADCOUNT_RESERVE,
	HUMAN_RESOURCES_PERMISSION_HEADCOUNT_EXCEPTIONAL_ADJUST,
	HUMAN_RESOURCES_PERMISSION_DOCUMENT_REQUIREMENT_MANAGE,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_DOCUMENT_OWN_READ,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_DOCUMENT_OWN_REGISTER,
	HUMAN_RESOURCES_PERMISSION_EMPLOYEE_DOCUMENT_VERIFY,
	HUMAN_RESOURCES_PERMISSION_WORK_ELIGIBILITY_VERIFY,
	HUMAN_RESOURCES_PERMISSION_COMPLIANCE_ADMINISTER,
	HUMAN_RESOURCES_PERMISSION_IDENTITY_DOCUMENT_SENSITIVE_READ,
	HUMAN_RESOURCES_PERMISSION_POLICY_ACKNOWLEDGEMENT_ADMINISTER,
	HUMAN_RESOURCES_PERMISSION_COMPETENCY_READ,
	HUMAN_RESOURCES_PERMISSION_COMPETENCY_MANAGE,
	HUMAN_RESOURCES_PERMISSION_COMPETENCY_ASSESS,
	HUMAN_RESOURCES_PERMISSION_CAREER_PLAN_OWN_READ,
	HUMAN_RESOURCES_PERMISSION_CAREER_PLAN_MANAGE,
	HUMAN_RESOURCES_PERMISSION_TALENT_ADMIN,
	HUMAN_RESOURCES_PERMISSION_TALENT_PROFILE_SENSITIVE_READ,
	HUMAN_RESOURCES_PERMISSION_SUCCESSION_ADMIN,
	HUMAN_RESOURCES_PERMISSION_SUCCESSION_EXECUTIVE_READ,
] as const;
